spring:
  application:
    name: auth-service
  config:
    import: configserver:http://root:password@localhost:8888/

#  datasource:
#    url: jdbc:postgresql://pgdb:5432/postgres
#    username: postgres
#    password: postgres
#    driverClassName: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddlAuto: update