spring:
  cloud:
    gateway:
      routes:
      - id: user-service
        uri: lb://user-service
        predicates:
          - Path=/users/**
      - id: job-service
        uri: lb://job-service
        predicates:
          - Path=/jobs/**
      - id: application-service
        uri: lb://application-service
        predicates:
          - Path=/applications/**
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true