server:
  servlet:
    context-path: /api/applications
  port: 8083
spring:
  application:
    name: application-service
  data:
    mongodb:
      uri: mongodb+srv://evstrelnikov:root@joblistingcluster.hoojkco.mongodb.net/?retryWrites=true&w=majority
      database: applications
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-service
