server:
  port: 9000
logging:
  level:
    org.springframework.security: trace
jwt:
  key:
    public: classpath:app.pub
    private: classpath:app.key
    id: serverkey
spring:
  security:
    user:
      name: user
      password: password
  datasource:
    url: jdbc:postgresql://localhost:5430/postgres
    username: postgres
    password: postgres
  sql:
    init:
      mode: always

#  data:
#    mongodb:
#      uri: mongodb+srv://evstrelnikov:root@joblistingcluster.hoojkco.mongodb.net/?retryWrites=true&w=majority
#      database: authentication