server:
  servlet:
    context-path: /api/jobs
  port: 8082
spring:
  application:
    name: job-service
  account-service:
    url: http://localhost:8080/accounts
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
  data:
    mongodb:
      uri: mongodb+srv://evstrelnikov:root@joblistingcluster.hoojkco.mongodb.net/?retryWrites=true&w=majority
      database: joblist