server:
  servlet:
    context-path: /users
  port: 8100
spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb+srv://evstrelnikov:root@joblistingcluster.hoojkco.mongodb.net/?retryWrites=true&w=majority
      database: users