server:
  servlet:
    context-path: /api/users
  port: 8081
spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb+srv://evstrelnikov:root@joblistingcluster.hoojkco.mongodb.net/?retryWrites=true&w=majority
      database: users
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-service